### ISSUE TITLE
Run this project 

### ISSUE THREAD

**Issue by Chuttyboy** [junaid340/AnomalyDetection-in-SurveillanceVideos#1]
Hello sir, 

First of all, thank you to uploading this code it's very useful for me. I am new to programming can you please help me to complete this project I have some doubts about anomaly detection.

Can you share how to run files and the steps involved in this project? and Share folder structure to extract feature

Thank you

**Comment by junaid340** [comment]
@Chuttyboy yeah sure what are your concerns?

**Comment by Chuttyboy** [comment]
> @Chuttyboy yeah sure what are your concerns?

Thank you so much, sir,

My Dataset Folder structure :

![folder_str](https://user-images.githubusercontent.com/79959547/127120609-ffe22abb-697e-4aef-98a4-9281260b04d3.png)

the run preprocessing file I got this error

![error_jun](https://user-images.githubusercontent.com/79959547/127120922-2d68f3fe-6976-4f1a-9808-3ac3674fbde5.png)

How to resolve it ?

Thank you

**Comment by junaid340** [comment]
> 
> 
> > @Chuttyboy yeah sure what are your concerns?
> 
> Thank you so much, sir,
> 
> My Dataset Folder structure :
> 
> ![folder_str](https://user-images.githubusercontent.com/79959547/127120609-ffe22abb-697e-4aef-98a4-9281260b04d3.png)
> 
> the run preprocessing file I got this error
> 
> ![error_jun](https://user-images.githubusercontent.com/79959547/127120922-2d68f3fe-6976-4f1a-9808-3ac3674fbde5.png)
> 
> How to resolve it ?
> 
> Thank you

As it says, there is some issue with the indexing... while we are extracting the names of file, in-line _109_ we are passing `names.append(file.split("\\")[1]` .... Check what is there in `file` and pass the accurate index value here!

Keep in mind we are trying to get the file names here! so we are splitting the string to do that!

**Comment by Chuttyboy** [comment]
> > > @Chuttyboy yeah sure what are your concerns?
> > 
> > 
> > Thank you so much, sir,
> > My Dataset Folder structure :
> > ![folder_str](https://user-images.githubusercontent.com/79959547/127120609-ffe22abb-697e-4aef-98a4-9281260b04d3.png)
> > the run preprocessing file I got this error
> > ![error_jun](https://user-images.githubusercontent.com/79959547/127120922-2d68f3fe-6976-4f1a-9808-3ac3674fbde5.png)
> > How to resolve it ?
> > Thank you
> 
> As it says, there is some issue with the indexing... while we are extracting the names of file, in-line _109_ we are passing `names.append(file.split("\\")[1]` .... Check what is there in `file` and pass the accurate index value here!
> 
> Keep in mind we are trying to get the file names here! so we are splitting the string to do that!

Thank You so much sir, Keep in touch for more clarifications

**Comment by anbuharry** [comment]
@junaid340 

Hello sir , I am getting same error, as you said i made change in code but i got error like process killed 

![junaid1](https://user-images.githubusercontent.com/54160097/129681213-7c53b227-b3a7-4eb5-9c20-f5c1b4ab2cbc.png)

![junaid2](https://user-images.githubusercontent.com/54160097/129684190-a31d9e1c-c14f-4527-acca-5eff716c22da.png)

Thank you

**Comment by junaid340** [comment]
hi @anbuharry, can you share the complete error log here please! and which OS are you using?

**Comment by Chuttyboy** [comment]
> hi @anbuharry, can you share the complete error log here please! and which OS are you using?

Hi @junaid340  sir I too have the same problem can you help us

OS: ubuntu 20
python: 3.8

cupy-cuda114==9.3.0
h5py==3.1.0
imageio==2.9.0
keras==2.6.0
Keras-Preprocessing==1.1.2
matplotlib==3.4.3
numpy==1.19.5
opencv-python==4.5.3.56
Pillow==7.0.0
pipenv==11.9.0
scikit-image==0.18.2
scipy==1.7.1
tensorboard==2.6.0
tensorflow-estimator==2.6.0
torch==1.9.0
torchvision==0.10.0
tqdm==4.62.1

Thank you

**Comment by Chuttyboy** [comment]
> hi @anbuharry, can you share the complete error log here please! and which OS are you using?

Hello sir,

Can you please help me to resolve this issue?

thank you

**Comment by junaid340** [comment]
@Chuttyboy the code was tested on Windows, I think the path splitter is different in Ubuntu; like in Windows we use directory path like this `Datasets/AvenueDataset/testing_videos` but the same in Ubuntu will be like this `Datasets\AvenueDataset\testing_videos`... Because you the error is with the splitters in file paths! That is why it's giving the `list index out of range` error! As nothing seems to be the issue on our side because everything is fine and the code runs fine on my system!

**Comment by anbuharry** [comment]
Hello,

Ok sir thanks for your reply I will check and update you

Thanks for you reply

**Comment by Chuttyboy** [comment]
> @Chuttyboy the code was tested on Windows, I think the path splitter is different in Ubuntu; like in Windows we use directory path like this `Datasets/AvenueDataset/testing_videos` but the same in Ubuntu will be like this `Datasets\AvenueDataset\testing_videos`... Because you the error is with the splitters in file paths! That is why it's giving the `list index out of range` error! As nothing seems to be the issue on our side because everything is fine and the code runs fine on my system!

Hai @junaid340 

Index out of range error solved but after after reading file process error happens , ok sir I will work  on it  

Thank you
